#!/usr/bin/python
# coding: utf8

LABEL_MAPPING_PREFIX={
  "I": "",
  "II": "",
  "III": "",
  "F1": "", # TODO: what do these codes mean?
  "F2": "",
  "G1": "",
  "G2": "",
  "Cactus": "",
  "Div": "",
  "Ebelin": "",
  "ebelin": "",
  "Ebel": "",
  "Fascino": "",
  "gefülltes": "",
  "Modul": "",
  "Natur": "",
  "Standard": "",
  "standard": "",
  "Sonstige": "",
  "sonstige": "",
  "sonstiges": "",
  "sonst": "",
  'Sonst': '',
  "4er": "",
  "dicke": "",
  "dünne": "",
  "ultra": "",
  'Univ': '',
  'Mini': '',
  "Zw": "", # means "in between" I guess?
  'Deko': 'Dekorative',
  'D': 'Damen',
  'F': 'Damen',
  'H': 'Herren',
  'M': 'Herren',
  'B': 'Baby',
  'K': 'child',
  'KW': 'child',
  'Elektr': 'elektrische',
  'Künstl': 'künstliche',
  'Chem': 'chemische',
  'Med': 'medizinische',
  'Kosm': 'kosmetische',
  'Flüss': 'flüssige',
}

LABEL_MAPPING_SUFFIX={
  '1': '',
  '2': '',
  '4er': '',
  'Standard': '',
  'allgemein': '',
  'S': '',
  'ST': '',
  'Set': '',
  'selbstklebend': '',
  'spezial': '',
  'feucht': '',
  'trocke': '',
  "fest": "",
  "flüssig": "",
  "ultra": "",
  'kbA': '',
  'Mode': '',
  'Natur': '',
  'vorportioniert': '',
  'Prof': '',
  ### TODO below unknown meaning
  'OT': '',
  'UT': '',
  'GP': '',
  'Bhf': '',
  'Mod': '',
}

LABEL_MAPPING_WORD={
  #### acronyms
  'KLKD': 'child clothing',
  'WPR': 'Haushalt item',
  'LM': 'Nahrung',
  'ZC': 'Zahncreme',
  'ZB': 'Zahnbürste',
  'HS': 'Haarschmuck',
  'MS': 'Modeschmuck',
  'HGSM': 'Spühlmittel',
  'MGSM': 'Spühlmittel',
  'HHN': 'Pflegeprodukt', # haut-haare-nase
  'WC': 'Toilette',
  'UWM': 'Waschmittel',
  'SpezialWM': 'Waschmittel',
  'HHfol': 'Haushaltsfolie',
  'FSH': 'Feinstrick Hose',
  #### abbreviations
  'Access': 'Accessoire',
  'Acc': 'Accessoire',
  'artik': 'Artikel',
  'Allzweckr': 'Allzweckreiniger',
  'Badean': 'Badeanzug',
  'Beaut': 'Beauty',
  'Belohn': 'Belohnung',
  'Brotaufstric': 'Brotaufstrich',
  'Brotauf': 'Brotaufstrich',
  'Butterbrotpa': 'Butterbrotpapier',
  'Deotüch': 'Deotücher',
  'Diagn': 'Diagnostik',
  'Einwegrasier': 'Einwegrasierer',
  'Entf': 'Entferner',
  'Faschingsart': 'Faschingsartikel',
  'Fensterdeko': 'Fensterdekoration',
  'flie': 'Stubenfliegen',
  'Fertiggeric': 'Fertiggericht',
  'Fußcre': 'Fußcreme',
  'Frischhaltef': 'Frischhaltefolie',
  'Gebißhaftmit': 'Gebißhaftmittel',
  'Gebißreinige': 'Gebißreiniger',
  'Gesundhe': 'Gesundheit',
  'Getr': 'Getreide',
  'Gefrierbeute': 'Gefrierbeutel',
  'Grußk': 'Grußkarte',
  'Haarent': 'Haarentferner',
  'Haush': 'Haushalt',
  'Haushaltshel': 'Haushaltshelfer',
  'Haushaltsfol': 'Haushaltsfolie',
  'Hunden': 'Hundefutter',
  'Hundenah': 'Hundefutter',
  'Ins': 'Insekten',
  'Insekt': 'Insekten',
  'Kalkrei': 'Kalkreiniger',
  'Katzenna': 'Katzenfutter',
  'Ker': 'Kerze',
  'Kerz': 'Kerze',
  'Kniestr': 'Kniestrümpfe',
  'Kreisla': 'Kreislauf',
  'Kerzengl': 'Kerzenglas',
  'Johanniskrau': 'Johanniskraut',
  'Lufterfrisch': 'Lufterfrischer',
  'Lebensm': 'Lebensmittel',
  'Magn': 'Magnesium',
  'Magnesiu': 'Magnesium',
  'Maschinenpfl': 'Maschinenpflege',
  'Manikü': 'Maniküre',
  'Miner': 'Mineralien',
  'Minera': 'Mineralien',
  'Mott': 'Motten',
  'Nagelackentf': 'Nagelackentferner',
  'Nerv': 'Nerven',
  'Pap': 'Papier',
  'Pflan': 'Pflanzen',
  'Pfl': 'Pflege',
  'Problemlö': 'Problemlöser',
  'Rasie': 'Rasierapparat',
  'Rasiervorber': 'Rasiervorbereitung',
  'Rasierzubeh': 'Rasierzubehör',
  'Rein': 'Reinigung',
  'Saiso': 'Saison',
  'So': 'Sommer',
  'Spezialreini': 'Spezialreiniger',
  'Spülm': 'Spülmittel',
  'Stärk': 'Stärkung',
  'Taschentüche': 'Taschentücher',
  'Teelichte': 'Teelichter',
  'Teppichreini': 'Teppichreiniger',
  'Toilettenpap': 'Toilettenpapier',
  'Toipa': 'Toilettenpapier',
  'Traubenzucke': 'Traubenzucker',
  'tro': 'trocken',
  'u': 'und',
  'Vitami': 'Vitamine',
  'Verdau': 'Verdauung',
  'Verba': 'Verbandszeug',
  'Verp': 'Verpackung',
  'Wasserenthär': 'Wasserenthärter',
  'Wi': 'Winter',
  'Zahnfl': 'Zahnfleisch',
  'Zubehö': 'Zubehör',
  'Zubeh': 'Zubehör',
  'Zube': 'Zubehör',
  'Zub': 'Zubehör',
  'Zungenreinig': 'Zungenreiniger',
  #### replacements
  'Bonbon': 'Süßigkeiten',
  'Deo': 'Parfüm',
  'Duschbäder': 'Duschgel',
  'Düfte': 'Parfüm',
  'Duft': 'Parfüm',
  'Feinstrick': 'clothing',
  'Geschenkpaier': 'Geschenkpapier',
  'Grobstrick': 'clothing',
  'Haushaltspap': 'Papier',
  'Hygienepapie': 'Papier',
  'Naturkosmetik': 'Kosmetik',
  'Pull': 'clothing', # TODO: what's the difference between push/pull?
  'Push': 'clothing',
  'SoBri': 'Sonnenbrille',
  'Zwischenverz': 'Nahrung',
  'verz': 'Nahrung',
  'NaWä': 'clothing',
  'TagWä': 'clothing',
  'Konfek': 'clothing',
  'Konf': 'clothing',
  #### delete words
  'Jumbopacks': '',
  'Spezialprod': '',
  'div': '',
  'XL': '',
  'Ja': '', # means "some season of the year"
  'klein': '',
  'maxi': '',
  'Maxi': '',
  'midi': '',
  'Prem': '',
  'Spez': '',
  '1tg': '',
  '2tg': '',
  'Zielg': '', # TODO: what does it mean
}

LABEL_MAPPING_REPLACE={
  ######### assortments
  'Dekorative Kosmetik': 'Pflegeprodukt',
  'Körperpflege':        'Pflegeprodukt',
  'Körperreinigung':     'cleaning agent',
  'Schönheitspa':        'Beauty Produkt',
  'Lebensmittel':        'Nahrung',
  'Accessoires':         'Accessoire item',
  'Ostern':              'Ostern Zubehör',
  'Weihnachten':         'Weihnachten Zubehör',
  'Tier':                'Tier item',
  'Baby':                'Baby item',
  'Haar':                'Haarpflege Produkt',
  'Haushalt':            'Haushalt item',
  'Kindertextil':        'child clothing',
  'Sonstiges':           '',
  ######### areas
  'Alltagshilfen': '',
  'Baby glas nahrung': 'Baby nahrung',
  'Babypflege': 'Baby Pflegeprodukt',
  'Bad': 'Badezimmer item',
  'Badaccessoires': 'Badezimmer item',
  'Biolebensmittel': 'Bio Nahrung',
  'Dekorative Displays': 'Dekoration',
  'Dienstleistung': '',
  'Beauty oder Maniküre': 'Pflegeprodukt',
  'Filter oder Folien': 'Haushalt item',
  'Flaschen oder Schnuller': 'Baby Zubehör',
  'Fuß': 'Fußpflege Produkt',
  'GeschenksetSchönheit': 'Beauty Produkt',
  'Gesicht': 'Gesichtspflege Produkt',
  'Hair': 'Haarpflege Produkt',
  'Haarpflege': 'Haarpflege Produkt',
  'Haarstyling': 'Haarstyling Produkt',
  'Hand': 'Handpflege Produkt',
  'Hund': 'Hund item',
  'Insekten oder Pflanzen': 'Insektizid',
  'Katze': 'Katze item',
  'Kinderwelt': 'child item',
  'Lekkerland M': 'Süßwaren',
  'Lesebrillen oder Modul Kontaktlinsen': 'Sehhilfe Produkt',
  'medizinische Pflege': 'Pflegeprodukt',
  'Mund Zahn': 'Pflegeprodukt',
  'Nagelkosmetik': 'Pflegeprodukt',
  'Nager': 'Nager item',
  'Nassrasur': 'Rasur item',
  'Kosmetik Modul': 'Pflegeprodukt',
  'Pharma': 'Pflegeprodukt',
  'Posten': 'Produkt',
  'Posten oder Saison': 'seasonal item',
  'Reform': 'Nahrung',
  'Schönheit': 'Beauty Produkt',
  'Sodastream': 'Ersatzteil', # TODO: this product has zero additional information
  'Sonne': 'Pflegeprodukt',
  'Sonstiges oder Te': '', # TODO: what is "Te"?
  'Vogel': 'Vogel item',
  'dekorative': 'Dekoration',
  ######### sub-areas
  'Aktionen': '',
  'frei von': '',
  'nicht verwendet': '',
  'Danke': '',
  'Gute Wünsche': '',
  'Werbeartikel': '',
  'Megapacks': '',
  'Feeling': '',
  'Abendbreie': 'Brei',
  'Breie': 'Brei',
  'Weisse Linie Glas': 'Babynahrung',
  'Loser Tee': 'Tee',
  'Reform Kost': 'health food',
  'Rooibostee': 'Tee',
  'Minikarte': 'Grußkarte',
  'Maxikarte': 'Grußkarte',
  'Reinigen Haushaltprodukt': 'Haushalt item',
  'Verhütung': 'Verhütungsmittel',
  'Saison': 'Saisonales Produkt',
  'Würzen': 'Gewürz',
  'Spezialdeos': 'Parfüm',
  'Herrendüfte': 'Herren Parfüm',
  'Damendüfte': 'Damen Parfüm',
  'Höschenwinde': 'Windel',
  'Wundheilung': 'Wundheilung Produkt',
  'Diagnostik': 'Diagnostik Produkt',
  'Augenpflege': 'Augenpflege Produkt',
  'Kosmetik': 'Kosmetik Produkt',
  'Beauty': 'Beauty Produkt',
  'No Name Schöheit': 'Beauty Produkt',
  'Fußpflege': 'Fußpflege Produkt',
  'Kosmetik Reinigung': 'cleaning agent',
  'Reinigen': 'cleaning agent',
  'medizinische Reinigung': 'cleaning agent',
  'Hochzeit': 'Hochzeit Zubehör',
  'Gesundheit': 'Gesundheit item',
  'Haarschmuck Saison': 'Haarschmuck',
  'Bäder': 'Badezimmer item',
  'Baby Wäsche': 'Baby clothing',
  'Kinder Wäsche': 'child clothing',
  'Kinder Kleidung': 'child clothing',
  'Kids oder Junior': 'child Produkt',
  'Damen': 'Women Product',
  'Herren': 'Men Product',
  'Juniormenü': 'child Nahrung',
  'Kindermenü': 'child Nahrung',
  'Kinderteller': 'child Nahrung',
  'Milchnahrung': 'Baby Nahrung',
  'Babymenü': 'Baby Nahrung',
  'Convenience': 'Nahrung',
  'Zubereitung': 'Nahrung',
  'Einmalbäder': 'Badezusatz',
  'kosmetische Bäder': 'Badezusatz',
  'medizinische Bäder': 'Badezusatz',
  'Erkältung': 'Erkältungsmittel',
  'Blase oder Niere': 'Gesundheitsprodukt',
  'Rheuma oder Musk': 'Gesundheitsprodukt',
  'Beruhig oder Nerven': 'Gesundheitsprodukt',
  'Aufbau oder Stärkung': 'Gesundheitsprodukt',
  'Inkontinenz': 'Inkontinenz Gesundheitsprodukt',
  'Kreislauf Chol': 'Kreislauf Gesundheitsprodukt', # TODO: what is "Chol"?
  'Magen oder Verdauung': 'Magen Gesundheitsprodukt',
  'Haut oder Haare oder N': 'Pflegeprodukt',
  'Haut oder Insekten': 'Pflegeprodukt',
  'Zahnseide oder H': 'Pflegeprodukt',
  'Besen oder Bürste': 'Pflegeprodukt',
  'Pflege': 'Pflegeprodukt',
  'Pflegen': 'Pflegeprodukt',
  'Kosmetik Pflege': 'Pflegeprodukt',
  'Apres Pflege': 'Pflegeprodukt',
  'Handpflege': 'Handpflege Produkt',
  'Taschentücher': 'Papiertaschentuch',
  'Tücher': 'Wischtuch',
  'Tücher oder Schwä': 'Wischtuch',
  'Sohlen': 'Schuhsohle',
  'Trinksauger': 'Babyflasche',
  'Creme Parfüm': 'Parfüm',
  'Augen m Entferner': 'Augen Make Up Entferner',
  'Tischdecken': 'table cloth',
  'Kleber oder Basteln': 'crafting tool',
  'Süßwaren': 'sweets',
  'Waschen Haushaltprodukt': 'household detergent',
  'Selbstbräuner': 'self tanning cream',
  'Problemlöser': 'Hilfsmittel',
  'Ratgeber oder Kinderbuch': 'Buch',
  'Damenhygiene': 'Damen Pflegeprodukt',
  'Getreide oder Saat oder Hü': 'Getreide',
  'Trauer': 'Trauer Zubehör',
  'Geburt oder Taufe': 'Geburtstag Zubehör',
  'Geburtstag': 'Geburtstag Zubehör',
  'Kindergeburtstag': 'Geburtstag Zubehör',
  'Windelzubehör': 'Baby Zubehör',
  'Media': 'Speichermedium',
  'Schlank Getränke': 'Getränk',
  'Sonne Sensitiv': 'Sonnenblocker',
  'Kindersonne': 'Sonnenblocker',
  'Prepaid': 'Prepaid Karte',
  'Foto': 'Fotozubehör',
  'Fotogeschenke': 'Fotozubehör',
  'Haushaltshelfer': 'Haushalt item',
  'Windelslips': 'Windel',
  'Schuh oder Imprägnierer': 'Schuhpflege Produkt',
  'Süßen oder Ref': 'Süßungsmittel', # TODO: what is "Ref"?
  ######### general-type
  'Windlichte': 'Windlicht',
  'Auge': 'Augenpflege Produkt',
  'Baby Gr clothing': 'Baby Clothing',
  'Babytee': 'Baby Tee',
  'Badserien': 'Badezimmer item',
  'Damenduft': 'Damen Parfüm',
  'Herrenduft': 'Herren Parfüm',
  'Damenkl': 'Rasierklinge',
  'Damenpflege': 'Damen Pflegeprodukt',
  'Einweg Dam': 'Einwegrasierer',
  'Binden': 'Monatsbinde',
  'Raumschmuck': 'Raumdekoration',
  'Ge Verpackung': 'Geschenkverpackung',
  'Katzen nass': 'Katzenfutter nass',
  'Nagernahrung': 'Nagerfutter',
  'Nahrung Refo': 'health food',
  'Haushalt item Helfer': 'Haushalt item',
  'Vor oder Zusatzb': 'cleaning agent',
  'Nass Rasiera': 'Nassrasierer',
  'Mitteldecken': 'Decke',
  'Fitneß': 'Fitneß Produkt',
  'Nagelpflege': 'Nagelpflege Produkt',
  'Bart': 'Bartpflege Produkt',
  'Herrenpflege': 'Herrenpflege Produkt',
  'Friesiermittel': 'Haarpflege Produkt',
  'Fußcreme oder gel': 'Fußpflege Produkt',
  'Pflegen Anti Age': 'Anti Age Pflegeprodukt',
  'Toilette Reinigung oder Pflege': 'Toilette Pflegeprodukt',
  'Pflegen Basis': 'Pflegeprodukt',
  'Pflegen Junge Haut': 'Pflegeprodukt',
  'Pflegen Männer': 'Herrenpflege Produkt',
  'Geschenkverpacung': 'Geschenkverpackungen',
  'Hundefutter trocken': 'dry dog food',
  'Konsum Zahncreme': 'Zahncreme',
  'Lippe': 'Lippenpflege Produkt',
  'Wimpern': 'Wimpern Produkt',
  'Dauerwellen': 'Dauerwellen Produkt',
  'Erotik': 'Erotik Produkt',
  'Instant Breie': 'Brei',
  'Lippenkosm Pflege': 'Lippenpflege Produkt',
  'Lippenkosmetik Zubehör': 'Lippenpflege Produkt',
  'künstliche Nägel Zubehör': 'fake nail accessory',
  'Basteln': 'tinker item',
  'Bänder': 'riboon',
  'Fußpilz': 'Fußpilz control agent',
  'Hornhaut': 'Hornhaut control agent',
  'Hühneraugen': 'Hühneraugen control agent',
  'Blasen': 'Brandblasen control agent',
  'Druckstellen': 'Druckstellen control agent',
  'Schrunden': 'Schrunden control agent',
  'Milben': 'Milben control agent',
  'Motten': 'Motten control agent',
  'Insekten flieg': 'Insektizid',
  'Insekten krie': 'Insektizid',
  'Chenille': 'Raumdekoration',
  'Desinfektion': 'Desinfektionsmittel',
  'Erf oder Deotücher': 'Erfrischungstücher',
  'Leggins oder Capri': 'Leggins',
  'French': 'Pflegeprodukt',
  'Faltshopper': 'Regenschirm',
  'Figuren': 'figurine',
  'Haarfestiger': 'hair mousse',
  'Intimpflege': 'intimate care product',
  'Reinigen Basis': 'cleaning agent',
  'Reinigen Junge Haut': 'cleaning agent',
  'Reinigen Männer': 'men cleaning agent',
  'Spezialreiniger': 'cleaning agent',
  'Schuh oder Kleid': 'clothing',
  'HHReiniger': 'household detergent',
  'Bad oder Kalkreiniger': 'bathroom detergent',
  'Figurenkerzen': 'Kerzen',
  'Mama': 'Baby Produkt',
  'Gel oder Wachs oder Cr': 'Haarstyling Produkt',
  'Teint': 'Teint Produkt',
  'Lebensmittel mott': 'Motten Köder',
  'Modullinsen': 'Kontaktlinsen',
  'No Name Geschenksets': 'Geschenkset',
  'Teefilter': 'Tee Filter',
  'Kerzenglas': 'Kerzen Container',
  'Zubehör Haushaltsfolie': 'Haushaltsfolie Zubehör',
  'Zubehör Toilettenpapier': 'Toilettenpapier Zubehör',
  'Zubehör Kerzen': 'Kerzen Zubehör',
  'Zubehör Sonnenbrille': 'Sonnenbrille Zubehör',
  'Superfood oder Protein': 'Nahrung',
  'Gästeseife oder Badeperle': 'Badezimmer item',
  'Kajal oder Liner': 'eye pencil',
  'Kleber und Basteln': 'tinker item',
  'Premiumkling': 'Rasierklinge',
  'Rasiergel': 'shaving gel',
  'Rasiervorbereitung': 'Rasier zubehör',
  'Rasierzubehör': 'Rasier zubehör',
  'Damenappa': 'Damen Rasierapparat',
  'el Damenapp': 'Damen Rasierapparat',
  'Geburtstag Humor': 'Geburtstag Grußkarte',
  'Hochzeit Humor': 'Hochzeit Grußkarte',
  'Geburtstag in Zahlen': 'Geburtstag Grußkarte',
  'Hochzeitstag oder Verlobung': 'Hochzeitstag oder Verlobung Zubehör',
  'Stumpensets': 'Kerzen',
  'Watte': 'cotton wool',
  'Nailstripes': 'Nail stripes',
  'Schleifen': 'Geschenkverpackung Schleifen',
  'Streudeko': 'Dekoration',
  'Eikerzen': 'Kerzen',
  'Über oder Unterlacke': 'Jacke',
  'Sommer Problemlöser': 'Hilfsmittel',
  'Folien': 'Haushaltsfolie',
  'Schlankkost': 'Nahrung',
  'Backen': 'Backzubehör',
  'Behang Sterne': 'Baumdekoration',
  'Eyeshadow': 'Augen Make Up',
  'Sommer Rheu oder Vene': 'Gesundheitsprodukt',
  'Leber oder Galle': 'Gesundheitsprodukt',
  'Interdental': 'Pflegeprodukt',
  'Baby Na Wä K': 'baby clothing',
  'Baby Tagwä K': 'baby clothing',
  'child Tagwä K': 'child clothing',
  ######### specific-type
}

