
SHOP_CLASS_REPLACEMENT={
  'Sock': 'Socks',
  'Tight': 'Tights',
  'Glove': 'Gloves',
  'Spice': 'Spices',
  'RooiboTea': 'RooibosTea',
  'CoughDrop': 'CoughDrops',
  'SunProtection': 'SunProtectionItem',
  'Zahncremes': 'Toothpaste',
  'WashingHouseholdItem': 'HouseholdCleaningItem',
  'CleanHouseholdItem': 'HouseholdCleaningItem',
  'Frame': 'PhotoFrame',
  'Phial': 'BabyBottle',
  'AlbumOrAccessory': 'PhotoAccessory',
  'RodentAccessory': 'RodentControlAgent',
  'GiftWrap': 'GiftWrapping'
}

SHOP_SUBCLASS_MAPPING={
    'SeasonalItem': [],
    ## Accessory stuff
    'AccessoryItem':      [],
    'HairAccessory':      ['AccessoryItem'],
    'SunglassAccessory':  ['AccessoryItem'],
    'Umbrella':           ['AccessoryItem'],
    'Sunglass':           ['AccessoryItem'],
    'TinkerAccessory':    ['AccessoryItem'],
    'WeddingAccessory':   ['AccessoryItem'],
    'BirthdayAccessory':  ['AccessoryItem'],
    'MourningAccessory':  ['AccessoryItem'],
    'CarnivalArticle':    ['AccessoryItem','SeasonalItem'],
    'ChristmasAccessory': ['AccessoryItem','SeasonalItem'],
    'TreeDecoration':     ['ChristmasAccessory'],
    'PhotoAccessory':     ['AccessoryItem'],
    'PhotoFrame':         ['PhotoAccessory'],
    ## Clothing stuff
    'Clothing':          [],
    'ClothingAccessory': ['Clothing','AccessoryItem'],
    'Socks':             ['Clothing'],
    'Tights':            ['Clothing'],
    'Gloves':            ['ClothingAccessory'],
    ## Food stuff
    'FoodOrDrink':     [],
    'Food':            ['FoodOrDrink'],
    'Beverage':        ['FoodOrDrink'],
    'YogurtCup':       ['ConvinienceFood'],
    'SqueezeBag':      ['Food'],
    'FrozenFood':      ['ConvinienceFood'],
    'ConvinienceFood': ['Food'],
    'SnackOrFruitBar': ['ConvinienceFood'],
    'Sweetener':       ['Food'],
    'HealthyFood':     ['Food'],
    'OrganicFood':     ['HealthyFood'],
    'Spread':          ['OrganicFood'],
    'Pasta':           ['OrganicFood'],
    'Spices':          ['OrganicFood'],
    'NutOrFruit':      ['OrganicFood'],
    'Vegetable':       ['OrganicFood'],
    'Grain':           ['OrganicFood'],
    'BakeryProduct':   ['OrganicFood'],
    'FruitOrCereal':   ['OrganicFood'],
    'Fruit':           ['FruitOrCereal'],
    'FruitCup':        ['Fruit','ConvinienceFood'],
    'Tea':             ['Beverage'],
    'GreenTea':        ['Tea'],
    'BlackTea':        ['Tea'],
    'FruitTea':        ['Tea'],
    'HerbalTea':       ['Tea'],
    'RooibosTea':      ['Tea'],
    'MedicinalTea':    ['Tea'],
    'Confectionery':   ['Food'],
    'IceCream':        ['Confectionery','FrozenFood','ConvinienceFood'],
    'CoughDrops':      ['Confectionery','HealthCareProduct'],
    'ChewingGum':      ['Confectionery'],
    'Glucose':         ['Confectionery'],
    ## Care products
    'CareProduct':        [],
    'BodyCareProduct':    ['CareProduct','BathroomItem'],
    'WomanCareProduct':   ['BodyCareProduct'],
    'ManCareProduct':     ['BodyCareProduct'],
    'MouthCareProduct':   ['BodyCareProduct'],
    'EyeCareProduct':     ['BodyCareProduct'],
    'FootCareProduct':    ['BodyCareProduct'],
    'HandCareProduct':    ['BodyCareProduct'],
    'FacialCareProduct':  ['BodyCareProduct'],
    'HairCareProduct':    ['BodyCareProduct'],
    'BodyLotion':         ['BodyCareProduct'],
    'DentureAdhesive':    ['MouthCareProduct'],
    'Coloration':         ['HairCareProduct'],
    'Cream':              ['BodyLotion'],
    'BodyOil':            ['BodyLotion'],
    'CareLotion':         ['BodyLotion'],
    'HealthCareProduct':             ['CareProduct'],
    'MedicalCareProduct':            ['HealthCareProduct'],
    'CirculatoryHealthCareProduct':  ['HealthCareProduct'],
    'VitaminOrMineral':              ['HealthCareProduct'],
    'ColdMedicine':                  ['HealthCareProduct'],
    'DiagnosticProduct':             ['HealthCareProduct'],
    'WoundHealingProduct':           ['HealthCareProduct'],
    'StomachHealthCareProduct':      ['HealthCareProduct'],
    'IncontinenceHealthCareProduct': ['HealthCareProduct'],
    'Balm':                          ['HealthCareProduct'],
    'Contraceptive':                 ['MedicalCareProduct'],
    'SunProtectionItem':             ['HealthCareProduct'],
    'SelfTanningCream':              ['SunProtectionItem'],
    ## Beauty products
    'BeautyProduct':      [],
    'Manicure':           ['BeautyProduct'],
    'Perfume':            ['BeautyProduct'],
    'PerfumePen':         ['Perfume'],
    'PerfumeScooter':     ['Perfume'],
    'PerfumeSpray':       ['Perfume'],
    'Atomizer':           ['Perfume'],
    'MakeUp':             ['BeautyProduct'],
    'EyeMakeUp':          ['MakeUp'],
    'LipCosmetic':        ['MakeUp'],
    'NailCosmetic':       ['MakeUp'],
    'MakeUpRemover':      ['BeautyProduct','Remover'],
    'EyeMakeUpRemover':   ['MakeUpRemover','FacialCareProduct'],
    'HairstylingProduct': ['BeautyProduct'],
    ## Cleaning stuff
    'CleaningProduct':       [],
    'ShoeCareProduct':       ['CleaningProduct'],
    'CleaningPaper':         ['CleaningProduct','Paper'],
    'KitchenTowel':          ['CleaningPaper'],
    'Tissue':                ['CleaningPaper'],
    'Napkin':                ['CleaningPaper'],
    'CottonProduct':         ['CleaningProduct'],
    'HandCleaningProduct':   ['CleaningProduct','HandCareProduct'],
    'HandSanitizer':         ['HandCleaningProduct'],
    'LiquidSoap':            ['HandCleaningProduct','Soap'],
    'NailPolishRemover':     ['HandCleaningProduct','Remover'],
    'Soap':                  ['CleaningProduct'],
    'MouthCleaningProduct':  ['CleaningProduct','MouthCareProduct'],
    'DentureCleaner':        ['MouthCleaningProduct'],
    'TongueCleaner':         ['MouthCleaningProduct'],
    'Toothpaste':            ['MouthCleaningProduct'],
    'CosmeticPaper':         ['CleaningProduct'],
    'CosmeticTowel':         ['CleaningProduct'],
    'Remover':               ['CleaningProduct'],
    ## control agents
    'ControlAgent':           [],
    'RodentControlAgent':     ['ControlAgent'],
    ## Household stuff
    'HouseholdItem':         [],
    'Anther':                ['HouseholdItem'],
    'Filter':                ['HouseholdItem'],
    'Lightbulb':             ['HouseholdItem'],
    'TableCloth':            ['HouseholdItem'],
    'HouseholdFoil':         ['HouseholdItem'],
    'GarbageBag':            ['HouseholdItem','ServiceProduct'],
    'HouseholdCleaningItem': ['HouseholdItem','CleaningProduct'],
    'Wipe':                  ['HouseholdCleaningItem'],
    'WiperSystem':           ['HouseholdCleaningItem'],
    'Duster':                ['HouseholdCleaningItem'],
    'BathroomItem':          ['HouseholdItem'],
    'SaunaInfusion':         ['BathroomItem'],
    'BathAdditive':          ['BathroomItem','BodyCareProduct'],
    'BathroomCleaningItem':  ['BathroomItem','CleaningProduct'],
    'ShowerGel':             ['BathroomCleaningItem','BodyCareProduct'],
    'Mouthwash':             ['BathroomCleaningItem','MouthCareProduct'],
    'Toothbrush':            ['BathroomCleaningItem','MouthCareProduct'],
    'ToothWhiteningSystem':  ['BathroomCleaningItem','MouthCareProduct'],
    'ToiletPaper':           ['BathroomCleaningItem','Paper'],
    'ShavingAccessory':      ['BathroomItem','AccessoryItem'],
    'ToiletCase':            ['BathroomItem'], # TODO what is a toilet case?
    ## Gender stuff
    'ManItem':        [],
    'WomanItem':      [],
    'ManPerfume':     ['ManItem','Perfume'],
    'WomanPerfume':   ['WomanItem','Perfume'],
    ## Baby stuff
    'BabyItem':         [],
    'BabyFood':         ['BabyItem','Food'],
    'BabyDrink':        ['BabyItem','Beverage'],
    'Mash':             ['BabyFood'],
    'BabyClothing':     ['Clothing','BabyItem'],
    'BabyCareProduct':  ['CareProduct','BabyItem'],
    'BabyAccessory':    ['BabyItem'],
    'Dummy':            ['BabyAccessory'],
    'BabyBottle':       ['BabyAccessory'],
    'DiaperAccessory':  ['BabyAccessory'],
    'Diaper':           ['BabyItem'],
    'FleeceDiaper':     ['Diaper'],
    ## Child stuff
    'ChildItem':        [],
    'ChildClothing':    ['Clothing','ChildItem'],
    'ChildLaundry':     ['ChildItem'],
    'ChildAccessory':   ['ChildItem'],
    'ChildFood':        ['Food'],
    ## Animal stuff
    'AnimalAccessory': ['AccessoryItem'],
    'DogAccessory':    ['AnimalAccessory'],
    'CatAccessory':    ['AnimalAccessory'],
    'BirdAccessory':   ['AnimalAccessory'],
    ## Problem solver
    'ProblemSolver':    [],
    'Insecticide':      ['ProblemSolver'],
    'Fertilizer':       ['ProblemSolver'], # TODO what is a Fertilizer
    'VisualAidProduct': ['ProblemSolver'],
    'ReadingGlass':     ['VisualAidProduct'],
    'ContactLens':      ['VisualAidProduct'],
    ## Other stuff
    'OtherProduct':   [],
    'ServiceProduct': ['OtherProduct'],
    'Candle':         ['OtherProduct'],
    'Curtain':        ['OtherProduct'],
    'Battery':        ['OtherProduct'],
    'Bag':            ['OtherProduct'],
    'Paper':          ['OtherProduct'],
    'WrappingPaper':  ['Paper'],
    'GiftWrapping':   ['Paper'],
    'Shoesole':       ['OtherProduct'],
    'Voucher':        ['OtherProduct'],
    'PrepaidCard':    ['OtherProduct'],
    'GreetingCard':   ['OtherProduct'],
    'StorageMedia':   ['OtherProduct'],
    'MediaProduct':   ['OtherProduct'],
    'Book':           ['MediaProduct'],
    'Movie':          ['MediaProduct'],
    'Decoration':     ['OtherProduct'],
    'SparePart':      ['OtherProduct'],
    'RoomDecoration': ['Decoration']
}
